<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>CONNECTION_OK_BUT_CREDENTIALS_LACK_PERMISSION</key>
        <language>uk</language>
        <message>З'єднання успішно встановлено&lt;p&gt;Однак облікові дані, що використовуються для підключення до віддаленого екземпляра, не дозволяють виконати цю операцію. Щоб вирішити цю проблему, виконайте одну з наведених нижче дій.&lt;ol&gt;&lt;li&gt;У локальному екземплярі змініть внесені в кеш облікові дані на облікові дані за участю адміністратора або teamdev_user.&lt;/li&gt;&lt;li&gt;У віддаленому екземплярі надайте облікові дані, що використовуються. ролі адміністратора або teamdev_user.&lt;/li&gt;&lt;/ol&gt;</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>bogdan.felinskyi</sys_created_by>
        <sys_created_on>2022-03-23 17:37:22</sys_created_on>
        <sys_id>c6ceb8271b96c910c069657bab4bcb3d</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>CONNECTION_OK_BUT_CREDENTIALS_LACK_PERMISSION</sys_name>
        <sys_package display_value="I18N: Ukrainian Translations" source="176ebda287b38910f4b131570cbb3551">176ebda287b38910f4b131570cbb3551</sys_package>
        <sys_policy/>
        <sys_scope display_value="I18N: Ukrainian Translations">176ebda287b38910f4b131570cbb3551</sys_scope>
        <sys_update_name>sys_ui_message_c6ceb8271b96c910c069657bab4bcb3d</sys_update_name>
        <sys_updated_by>bogdan.felinskyi</sys_updated_by>
        <sys_updated_on>2022-03-23 17:37:22</sys_updated_on>
    </sys_ui_message>
</record_update>
